# Lychee link checker configuration

# Exclude common local or dynamic URLs
exclude = [
  "http://localhost",
  "https://localhost",
  "http://127.0.0.1",
  "https://127.0.0.1",
  "app://*",
  "file://*"
]

# Accept 429 rate limits without failing
accept = [429]

# Set a reasonable timeout
timeout = 20

# Retry policy
max_retries = 2
retry_wait_time = 2

# GitHub token is provided via env in the workflow
