version: '3.9'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: notebooklm_postgres
    environment:
      POSTGRES_USER: notebook
      POSTGRES_PASSWORD: notebook
      POSTGRES_DB: notebook
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notebook"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama:
    image: ollama/ollama:latest
    container_name: notebooklm_ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  ollama:
